#!/usr/bin/env bash

function main {
  set -e

  local -r from_directory="$1"
  local -r to_directory="$2"

  set -x

  exiftool \
    -ignoreMinorErrors \
    -out . \
    -verbose \
    -dateFormat "$to_directory"/%Y/%Y-%m-%d \
    '-Directory<DateTimeOriginal' \
    "$from_directory"
}

main "$1" "$2"
