#!/usr/bin/env bash

# Create sidecar file for RAF photos in specified directory, and copy all metadata from photo to sidecar
function main {
  local -r directory="$1"

  # shellcheck disable=2016
  exiftool \
    -ignoreMinorErrors \
    -overwrite_original_in_place \
    -verbose \
    -extension 'RAF' \
    -tagsFromFile '@' \
    -srcfile '%d%f.xmp' \
    "$directory"
}

main "$1"
