#!/usr/bin/env bash

function main {
  local -r photos="$1"
  local -r one_week_ago=$(gdate -d '1 week ago' +%Y-%m-%d)

  set -x

  download-tracks "$one_week_ago:"
  geotag-photos "$photos"
}

main "$1"
