#!/usr/bin/env bash

PATH=~/Pictures/Scripts/:"$PATH"

function main {
  set -e

  local -r card="X-T5 #1"
  local -r photos=~/Pictures/Photographs
  local -r photos_for_review="$photos/Ready for review"

  set -x

  backup-new-imports
  update-new-imports-metadata
  move-and-rename-newly-imported-photos
  open-in-bridge "$photos_for_review"
  unmount-card "$card"
}

main
