#!/usr/bin/env bash

PATH=~/Pictures/Scripts/:"$PATH"

function main {
  set -e

  local -r card="X-T5 #1"
  local -r photos=~/Pictures/Photographs
  local -r import_backups="$photos"/Originals
  local -r newly_imported_photos="$photos"/Importing
  local -r photos_for_review="$photos/Ready for review"

  set -x

  backup-imports "$newly_imported_photos" "$import_backups"
  update-metadata "$newly_imported_photos"
  move-and-rename "$newly_imported_photos" "$photos_for_review"
  open-in-bridge "$photos_for_review"
  # erase-photos-from-card "$card"
  unmount-card "$card"
}

main
