#!/usr/bin/env bash

PATH="/Users/hpg/Pictures/Scripts/:/opt/homebrew/bin:$PATH"

function main {
  set -x

  backup-new-imports
  update-new-imports-metadata
  move-and-rename-newly-imported-photos
  open-new-imports-for-review
  unmount-card
}

time-log main
