#!/usr/bin/env bash

function main {
  echo 'finish-review: Newly imported photos have been reviewed (rejected and selected)'

  trash-rejected-photos
  move-and-import-selected-photos
  move-reviewed-photos
}

main
