#!/usr/bin/env bash

function main {
  echo 'finish-review: Newly imported photos have been reviewed (rejected and selected)'

  trash-rejected-photos
  move-and-import-selected-photos

  echo ''
  echo '----------------------------------------------------------------------'
  echo '  Done importing selects into Lightroom?'
  echo ''
  echo '  Press any key to move all remaining reviewed photos to the catalog'
  echo '    or control-c to cancel... '
  read -p '----------------------------------------------------------------------' -n1 -r -s
  echo ''

  move-reviewed-photos
}

main
