#!/usr/bin/env bash

function main {
  local -r cc_app_name="/Applications/Adobe Lightroom CC/Adobe Lightroom.app"
  local -r classic_app_name="/Applications/Adobe Lightroom Classic/Adobe Lightroom Classic.app"

  local -ar full_paths_for_importing=("$@")

  echo 'import-into-lightrooms: Opening photo and sidecar files in Lightroom Classic'
  echo "+ open ${full_paths_for_importing[*]} -a \"$classic_app_name\""
  open  "${full_paths_for_importing[@]}" -a "$classic_app_name"

  echo ''
  echo '----------------------------------------------------------------'
  echo '  Done importing selects into Lightroom Classic?'
  echo ''
  echo '  !! Be sure to wait for the imports to sync with the cloud !!'
  echo ''
  echo '  Press any key to import selects into Lightroom CC'
  echo '    or control-c to cancel... '
  read -p '----------------------------------------------------------------' -n1 -r -s
  echo ''
  echo ''

  echo 'import-into-lightrooms: Opening photo and sidecar files in Lightroom CC'
  echo "open  ${full_paths_for_importing[*]} -a \"$cc_app_name\""
  open  "${full_paths_for_importing[@]}" -a "$cc_app_name"
}

main "$@"
