#!/usr/bin/env bash

function main {
  local -r photos=~/Pictures/Photographs
  local -r review_directory="$photos/Ready for review"

  set -x

  # shellcheck disable=2016
  exiftool \
    -ignoreMinorErrors \
    -verbose \
    -dateFormat "$photos"/%Y/%Y-%m-%d/%%f.%%e \
    '-filename<CreateDate' \
    "$review_directory"
}

main
