#!/usr/bin/env bash

function main {
  local -r from_directory="$1"
  local -r to_directory="$2"

  set -ex

  # -dateFormat "$to_directory"/%Y/%Y-%m-%d/%Y%m%d-%%f.%%e \
  exiftool \
    -ignoreMinorErrors \
    -verbose \
    -dateFormat "$to_directory/%Y%m%d-%%f.%%e" \
    '-filename<CreateDate' \
    "$from_directory"
}

main "$1" "$2"
