#!/usr/bin/env bash

function main {
  local -r imports_directory=~/Pictures/Photographs/Importing
  local -r review_directory=~/Pictures/Photographs/'Ready for review'

  set -x

  # shellcheck disable=2016
  exiftool \
    -ignoreMinorErrors \
    -verbose \
    -dateFormat "$review_directory"/%Y%m%d-%%f.%%e \
    '-filename<CreateDate' \
    "$imports_directory"
}

main
