#!/usr/bin/env bash

function main {
  local -r imports_directory=~/Pictures/Photographs/Importing
  local -r review_directory=~/Pictures/Photographs/'Ready for review'

  set -x

  # shellcheck disable=2016
  exiftool \
    -ignoreMinorErrors \
    -verbose \
    -DateFormat "$review_directory"/%Y%m%d-%%f.%%e \
    '-FileName<DateTimeOriginal' \
    "$imports_directory"

  echo "exiftool exit status: $?"
}

main
