#!/usr/bin/env bash

function main {
  local -r year="$(date +%Y)"
  local -r log_directory=~/Pictures/Photographs/Logs/"$year"
  local -r log_file="$log_directory/$(date-iso8601-ish)-selected.csv"
  local -r photos=~/Pictures/Photographs
  local -r review_directory="$photos/Reviewing"

  local -a exiftool_output
  local -a full_paths_for_importing

  echo 'move-and-import-selected-photos: Moving all selected photos (≥ 1 rating) and their sidecars from Reviewing/YYYY-mm-dd-*.{RAF,xmp} to their permanent home at YYYY/YYYY-mm-dd/YYYY-mm-dd-*.{RAF,xmp}'
  echo 'move-and-import-selected-photos: Importing them all into Lightroom Classic, waiting for keyboard confirmation, then importing them all (again) into Lightroom CC'
  echo "move-and-import-selected-photos: Logging the changes to $log_file"

  mkdir -p "$log_directory"
  touch "$log_file"
  # Log headers
  echo 'Path to photo,Path to sidecar' >> "$log_file"

  # Run it in TestName mode (dry run) to capture which photos have been selected, ie have a rating of ≥ 1 (details below)
  mapfile -t exiftool_output < <( \
    # shellcheck disable=2016
    exiftool \
      -ignoreMinorErrors \
      -quiet \
      -extension 'xmp' \
      -if '$Rating ge 1' \
      -dateFormat "$photos"/%Y/%Y-%m-%d/%%f.%%e \
      '-TestName<DateTimeOriginal' \
      "$review_directory"
  )

  # Each line looks like (.xmp only):
  #   '/Users/hpg/Pictures/Photographs/Reviewing/2023-01-24-DSCF9994.xmp' --> '/Users/hpg/Pictures/Photographs/2023/2023-01-24/2023-01-24-DSCF9994.xmp'
  for selected_file in "${exiftool_output[@]}"; do
    local destination_directory_path
    local full_path_without_extension
    local review_path_without_extension
    local short_path

    # Get the reviewed photo's full path (without extension):
    #   /Users/hpg/Pictures/Photographs/Reviewing/2023-01-24-DSCF9994
    review_path_without_extension=$( \
      echo "$selected_file" \
        | awk -F "'" '{print $2}' \
        | cut -d . -f 1
    )

    # Get the photo's full destination path (without extension):
    #   /Users/hpg/Pictures/Photographs/2023/2023-01-24/2023-01-24-DSCF9994
    full_path_without_extension=$( \
      echo "$selected_file" \
        | awk -F "'" '{print $4}' \
        | cut -d . -f 1
    )

    # Get the photo's short destination path (relative to ~/Picutures/Photographs, without extension):
    #   2023/2023-01-24/2023-01-24-DSCF9994
    short_path=$( \
      echo "$full_path_without_extension" \
        | awk -F 'Photographs/' '{print $2}'
    )

    # Get the photo's full destination directory path:
    #   /Users/hpg/Pictures/Photographs/2023/2023-01-24/
    destination_directory_path="${full_path_without_extension%/*}/"

    # Log the short destination paths
    echo "$short_path.RAF,$short_path.xmp" >> "$log_file"

    # Keep track of the full destination paths (both photos and sidecars), for importing into the apps below
    full_paths_for_importing+=("$full_path_without_extension".RAF "$full_path_without_extension".xmp)

    # Ensure the destination directory exists
    mkdir -p "$destination_directory_path"

    # Move the photo and sidecar files from the review folder to their permanent home
    mv -v "$review_path_without_extension".{RAF,xmp} "$destination_directory_path"

    # Subtract 1 from the photo's rating (stored in the sidecar)
    # shellcheck disable=2016
    exiftool \
      -ignoreMinorErrors \
      -overwrite_original_in_place \
      -'XMP-xmp:Rating<${XMP-xmp:Rating#;$_-=1}' \
      "$full_path_without_extension".xmp
  done

  import-into-lightrooms "${full_paths_for_importing[@]}"
}

main
