#!/bin/bash

function main {
  local -r bridge_app_name="Adobe Bridge 2023"
  local -r photos="$1"

  set -ex

  if pgrep "$bridge_app_name"; then
    osascript -e "quit app \"$bridge_app_name\""
    sleep 5
  fi

  open "/Applications/$bridge_app_name/$bridge_app_name.app" --args "$photos"
}

main "$1"
