#!/bin/bash

function main {
  local -r review_app='FastRawViewer.app'
  local -r photos=~/Pictures/Photographs/Reviewing

  echo "open-new-imports-for-review: Opening all newly imported photos in $review_app"

  set -ex

  open "$photos" -a "/Applications/$review_app"
}

main
