#!/usr/bin/env bash

function main {
  local log_name
  log_name=$(basename "$1")
  local -r log=~/Pictures/Scripts/logs/"${log_name}-$(date-iso8601-ish)"

  echo "plain-log: Logging $log_name to $log"

  set -x

  "$@" > "$log" 2>&1
}

main "$1"
