#!/usr/bin/env bash

function main {
  local log_name
  if [[ "$2" == 'main' ]]; then
    log_name="$1"
    shift
  else
    log_name=$(basename "$1")
  fi
  local -r log=~/Pictures/Scripts/logs/"${log_name}-$(date-iso8601-ish)"

  set -x

  "$@" > "$log" 2>&1
}

main "$1"
