#!/usr/bin/env bash

function main {
  local -r year="$(date +%Y)"
  local -r photos=~/Pictures/Photographs
  local -r log_directory="$photos"/Logs/"$year"
  local log_file

  local log_file_or_number="$1"
  if [[ "$log_file_or_number" =~ ^[1-9]+$ ]]; then
    # shellcheck disable=2086
    log_file="$(find "$log_directory"/*-selected.csv | tail -n $log_file_or_number | head -n 1)"
  else
    if [[ ! -f "$log_file_or_number" ]]; then
      log_file="$log_directory/$1"
    elif [[ ! -f "$log_file_or_number" ]]; then
      log_file="$(find "$log_directory"/*-selected.csv | tail -n 1)"
    else
      echo "reimport-selects-from-log: No select log file file found for '$log_file'"
      exit 42
    fi
  fi

  local -a paths_for_importing
  mapfile -t paths_for_importing < <(qsv behead "$log_file" | qsv fmt -t ' ' | tr ' ' '\n')
  local -ar full_paths_for_importing=("${paths_for_importing[@]/#/$photos/}")

  local -a existent_full_paths_for_importing
  local -a non_existent_full_paths_for_importing
  local some_files_are_missing
  for path in "${full_paths_for_importing[@]}"; do
    if [[ -f "$path" ]]; then
      existent_full_paths_for_importing+=("$path")
    else
      some_files_are_missing='true'
      non_existent_full_paths_for_importing+=("$path")
    fi
  done

  echo "reimport-selects-from-log: Re-importing selected photos from $log_file"

  if [[ "$some_files_are_missing" ]]; then
    echo "reimport-selects-from-log: The following files no longer exist, and are being ignored:"
    printf '%s\n' "${non_existent_full_paths_for_importing[@]}"
  fi

  import-into-lightrooms "${existent_full_paths_for_importing[@]}"
}

main "$1"
