#!/usr/bin/env bash

function main {
  local log_name
  log_name=$(basename "$1")
  local -r log=/Users/hpg/Pictures/Scripts/logs/"${log_name}-$(date-iso8601-ish)"

  echo "time-log: Logging $log_name to $log with timestamps"

  set -x

  "$@" |& ts %H:%M:%.S > "$log" 2>&1
}

main "$@"
