#!/usr/bin/env bash

function iso8601 {
  date +%Y-%m-%dT%H:%M:%S
}

function main {
  set -x

  local log_name
  if [[ "$2" == 'main' ]]; then
    log_name="$1"
    shift
  else
    log_name=$(basename "$1")
  fi
  local -r log=/Users/hpg/Pictures/Scripts/logs/"${log_name}-$(iso8601)"

  "$@" |& ts %H:%M:%.S > "$log" 2>&1
}

main "$@"
