#!/usr/bin/env bash

function iso8601 {
  date +%Y-%m-%dT%H:%M:%S
}

function main {
  local -r log_name=$(basename "$1")
  local -r log=/Users/hpg/Pictures/Scripts/logs/"${log_name}-$(iso8601)"

  set -x

  "$@" |& ts %H:%M:%.S > "$log" 2>&1
}

main "$@"
