#!/usr/bin/env bash

function main {
  local -r year="$(date +%Y)"
  local -r log_directory=~/Pictures/Photographs/Logs/"$year"
  local -r log_file="$log_directory/$(date-iso8601-ish)-rejected.csv"
  local -r review_directory=~/Pictures/Photographs/'Ready for review'

  local -a exiftool_output

  mkdir -p "$log_directory"
  touch "$log_file"
  echo 'Photo filename,Sidecar filename' >> "$log_file"

  mapfile -t exiftool_output < <( \
    # shellcheck disable=2016
    exiftool \
      -ignoreMinorErrors \
      -printFormat '$FileName' \
      -quiet \
      -if '$Rating eq -1' \
      "$review_directory" \
        | cut -d . -f 1
  )

  for rejected_file in "${exiftool_output[@]}"; do
    echo "$rejected_file.RAF,$rejected_file.xmp" >> "$log_file"
    trash -v "$review_directory/$rejected_file".{RAF,xmp}
  done
}

main
