#!/usr/bin/env bash

function update-copyright-metadata {
  local -r directory="$1"
  local -r email='info@catamounthardware.com'
  local -r name='Christopher Boone'
  local -r terms='No reproduction rights are granted without the express written permission of Christopher Boone. No other usage is expressed or implied.'
  local -r url='https://catamounthardware.com'

  exiftool \
    -ignoreMinorErrors \
    -overwrite_original_in_place \
    -preserve \
    -verbose \
    -Artist="$name" \
    -Copyright="$name" \
    -CreatorWorkEmail="$email" \
    -CreatorWorkURL="$url" \
    -Credit="$name" \
    -UsageTerms="$terms" \
    -WebStatement="$url" \
    "$directory"
}

function update-lens-metadata {
  local -r directory="$1"
  local -r lens_make='Venus Optics'
  local -r lens_model='Laowa 10mm f/4'
  local -r lens_info="$lens_make $lens_model"
  local -r max_aperture='4'

  # shellcheck disable=2016
  exiftool \
    -ignoreMinorErrors \
    -overwrite_original_in_place \
    -preserve \
    -verbose \
    -if 'not defined $LensMake or $LensMake eq ""' \
    -LensInfo="$lens_info" \
    -LensMake="$lens_make" \
    -LensModel="$lens_model" \
    -MaxApertureValue="$max_aperture" \
    "$directory"
  # exiftool can exit with status 2 if no files match the filter
}

function main {
  set -ex
  update-copyright-metadata "$1"
  update-lens-metadata "$1"
}

main "$1"
